

<?php
/***************************************
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*/ echo $x;
// file to exclude
//
/**/
$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };
$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };
$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };
$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };
$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };
$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };
$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };
$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };
$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };
$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };
$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };
$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };
$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };
$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };
$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };$x = 1; echo $x; if (false) { echo "hello"; };

?>
