name: Automate release

on:
  workflow_dispatch:
    inputs:
      short-description:
        description: |
          A brief summary of what the release contains.
          This will be added directly to the release ticket.
        required: true
      rule_properties_changed:
        type: choice
        description: |
          Did any rule properties change in this release?
        required: true
        default: "No"
        options:
          - "Yes"
          - "No"
      sq_compatibility:
        description: |
          SonarQube compatibility.
          Default needs to be changed only in case of LTA fix release.
        default: ">=10.8"
        required: true
      branch:
        description: |
          Branch from which to do the release.
        required: true
        default: "master"
      next_version:
        description: |
          Specify the version for the next release (e.g., 4.2.0).
          If left blank, the minor version will be automatically incremented.
        required: false
      jira_release_name:
        description: |
          The name of the release version in Jira.
          If blank, the action will try to use the *only* unreleased version in the project.
        required: false
      sonarlint_changelog:
        description: |
          A summary of release notes relevant to the SonarQube IDE extensions.
        required: false

jobs:
  automated-release:
    uses: SonarSource/release-github-actions/.github/workflows/cloud-security-automated-release.yml@yp/add_cloud_security_workflow
    permissions:
      statuses: read
      id-token: write
      contents: write
      actions: write
      pull-requests: write
    with:
      jira-project-key: "SONARPHP"
      project-name: "SonarPHP"
      plugin-name: "php"
      use-jira-sandbox: true
      is-draft-release: true
      pm-email: "yasen.pavlov@sonarsource.com"
      release-automation-secret-name: "sonar-php-release-automation"
      short-description: ${{ inputs.short_description }}
      sq-compatibility: ${{ inputs.sq_compatibility }}
      branch: ${{ inputs.branch }}
