name: Automate release

env:
  JIRA_PROJECT_KEY: "SONARPHP"
  PROJECT_NAME: "SonarPHP"
  USE_JIRA_SANDBOX: true
  PM_EMAIL: 'yasen.pavlov@sonarsource.com'

on:
  workflow_dispatch:
    inputs:
      short_description:
        description: |
          A brief summary of what the release contains. 
          This will be added directly to the release ticket.
        required: true
      rule_properties_changed:
        type: choice
        description: |
          Did any rule properties change in this release?
        required: true
        default: "No"
        options:
          - "Yes"
          - "No"
      sq_compatibility:
        description: |
          SonarQube compatibility.
          Default needs to be changed only in case of LTA fix release.
        default: ">=10.8"
        required: true
      next_version:
        description: |
          Specify the version for the next release (e.g., 4.2.0).
          If left blank, the minor version will be automatically incremented.
        required: false
      jira_release_name:
        description: |
          The name of the release version in Jira.
          If blank, the action will try to use the *only* unreleased version in the project.
        required: false
      sonarlint_changelog:
        description: |
          A summary of release notes relevant to the SonarQube IDE extensions.
        required: false

jobs:
  create_release_ticket:
    name: Create release ticket
    runs-on: ubuntu-latest
    permissions:
      statuses: read
      contents: read
      id-token: write
    outputs:
      release-ticket-key: ${{ steps.create_ticket.outputs.release-ticket-key }}
    steps:
      - name: Create Jira Release Ticket
        id: create_ticket
        uses: SonarSource/release-github-actions/create-jira-release-ticket@master
        with:
          project-name: ${{ env.PROJECT_NAME }}
          short-description: ${{ github.event.inputs.short_description }}
          sq-compatibility: ${{ github.event.inputs.sq_compatibility }}
          rule-props-changed: ${{ github.event.inputs.rule_properties_changed }}
          sonarlint-changelog: ${{ github.event.inputs.sonarlint_changelog }}
          use-jira-sandbox: 'true'

  create_integration_tickets:
    name: Create SC integration ticket
    runs-on: ubuntu-latest
    needs: create_release_ticket
    permissions:
      statuses: read
      contents: read
      id-token: write
    steps:
      - id: get_release_version
        name: Get release version
        uses: SonarSource/release-github-actions/get-release-version@master

      - id: create_sqs_ticket
        name: Create SQS ticket
        uses: SonarSource/release-github-actions/create-integration-ticket@nw/add-create-integration-ticket-action
        with:
          linked-ticket-key: ${{needs.create_release_ticket.outputs.release-ticket-key }}
          jira-project-key: 'SC'
          release-version: ${{ steps.get_release_version.outputs.release-version }}
          analyzer-name: 'php'
          ticket-description: 'Test description'
          use-jira-sandbox: 'true'
