name: Automate release

env:
  JIRA_PROJECT_KEY: "SONARPHP"
  PROJECT_NAME: "SonarPHP"
  PM_EMAIL: 'yasen.pavlov@sonarsource.com'
  BUILD_NUMBER: '3.49.0.13536'

on:
  workflow_dispatch:
    inputs:
      short_description:
        description: |
          A brief summary of what the release contains. 
          This will be added directly to the release ticket.
        required: true
      rule_properties_changed:
        type: choice
        description: |
          Did any rule properties change in this release?
        required: true
        default: "No"
        options:
          - "Yes"
          - "No"
      sq_compatibility:
        description: |
          SonarQube compatibility.
          Default needs to be changed only in case of LTA fix release.
        default: ">=10.8"
        required: true
      next_version:
        description: |
          Specify the version for the next release (e.g., 4.2.0).
          If left blank, the minor version will be automatically incremented.
        required: false
      jira_release_name:
        description: |
          The name of the release version in Jira.
          If blank, the action will try to use the *only* unreleased version in the project.
        required: false
      sonarlint_changelog:
        description: |
          A summary of release notes relevant to the SonarQube IDE extensions.
        required: false

jobs:
  create_release_ticket:
    name: Create release ticket
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # Required for authenticating to Vault
    steps:
      - name: Create Jira Release Ticket
        id: create_ticket
        uses: SonarSource/release-github-actions/create-jira-release-ticket@2a3485bfb45f9ac4c45b154ddf24b3b146707458
        with:
          project-name: ${{ env.PROJECT_NAME }}
          short-description: ${{ github.event.inputs.short_description }}
          sq-compatibility: ${{ github.event.inputs.sq_compatibility }}
          rule-props-changed: ${{ github.event.inputs.rule_properties_changed }}
          sonarlint-changelog: ${{ github.event.inputs.sonarlint_changelog }}


  summarize_release:
    name: Release
    runs-on: ubuntu-latest
    needs: [ create_release_ticket ]
    steps:
      - name: Post Summary to Workflow
        run: |
          echo "**Summary of the release:**" >> $GITHUB_STEP_SUMMARY
          echo "- **BUILD_NUMBER:** ${{ env.BUILD_NUMBER }}" >> $GITHUB_STEP_SUMMARY
          echo "- **JIRA_VERSION:** ${{ env.JIRA_VERSION }}" >> $GITHUB_STEP_SUMMARY
          echo "- **RELEASE_TICKET_KEY:** ${{ env.RELEASE_TICKET_KEY }}" >> $GITHUB_STEP_SUMMARY
          echo "- **RELEASE_TICKET_URL:** ${{ env.RELEASE_TICKET_URL }}" >> $GITHUB_STEP_SUMMARY
          echo "- **JIRA_RELEASE_URL:** ${{ env.JIRA_RELEASE_URL }}" >> $GITHUB_STEP_SUMMARY
          echo "- **RELEASE_NOTES:** ${{ env.RELEASE_NOTES }}" >> $GITHUB_STEP_SUMMARY
