name: Automate release

env:
  JIRA_PROJECT_KEY: "SONARPHP"
  PROJECT_NAME: "SonarPHP"
  PM_EMAIL: 'yasen.pavlov@sonarsource.com'

on:
  workflow_dispatch:
    inputs:
      short_description:
        description: |
          A brief summary of what the release contains. 
          This will be added directly to the release ticket.
        required: true
      rule_properties_changed:
        type: choice
        description: |
          Did any rule properties change in this release?
        required: true
        default: "No"
        options:
          - "Yes"
          - "No"
      sq_compatibility:
        description: |
          SonarQube compatibility.
          Default needs to be changed only in case of LTA fix release.
        default: ">=10.8"
        required: true
      next_version:
        description: |
          Specify the version for the next release (e.g., 4.2.0).
          If left blank, the minor version will be automatically incremented.
        required: false
      jira_release_name:
        description: |
          The name of the release version in Jira.
          If blank, the action will try to use the *only* unreleased version in the project.
        required: false
      sonarlint_changelog:
        description: |
          A summary of release notes relevant to the SonarQube IDE extensions.
        required: false

jobs:
  check_releasability_status:
    name: Get release notes
    runs-on: ubuntu-latest
    permissions:
      statuses: read
    steps:
      - name: Check Releasability Status
        uses: SonarSource/release-github-actions/check-releasability-status@yasen/update_check-releasability-status_action
        with:
          with-optional-checks: 'false'

  get_release_notes:
    name: Get release notes
    runs-on: ubuntu-latest
    permissions:
      statuses: read
      contents: read
      id-token: write
    steps:
      - name: Get Jira Release Notes
        id: jira-notes
        uses: SonarSource/release-github-actions/get-jira-release-notes@yasen/update_check-releasability-status_action

      - name: Use the outputs
        run: |
          echo "Release Notes URL: ${{ steps.jira-notes.outputs.jira-release-url }}"
          echo "Release Notes:"
          echo "${{ steps.jira-notes.outputs.release-notes }}" 

  create_release_ticket:
    name: Create release ticket
    runs-on: ubuntu-latest
    permissions:
      statuses: read
      contents: read
      id-token: write
    steps:
      - name: Create Jira Release Ticket
        id: create_ticket
        uses: SonarSource/release-github-actions/create-jira-release-ticket@yasen/update_check-releasability-status_action
        with:
          project-name: ${{ env.PROJECT_NAME }}
          short-description: ${{ github.event.inputs.short_description }}
          sq-compatibility: ${{ github.event.inputs.sq_compatibility }}
          rule-props-changed: ${{ github.event.inputs.rule_properties_changed }}
          sonarlint-changelog: ${{ github.event.inputs.sonarlint_changelog }}
