name: Automate release

env:
  JIRA_PROJECT_KEY: "SONARPHP"
  PROJECT_NAME: "SonarPHP"
  USE_JIRA_SANDBOX: true
  PM_EMAIL: 'yasen.pavlov@sonarsource.com'

on:
  workflow_dispatch:
    inputs:
      short_description:
        description: |
          A brief summary of what the release contains. 
          This will be added directly to the release ticket.
        required: true
      rule_properties_changed:
        type: choice
        description: |
          Did any rule properties change in this release?
        required: true
        default: "No"
        options:
          - "Yes"
          - "No"
      sq_compatibility:
        description: |
          SonarQube compatibility.
          Default needs to be changed only in case of LTA fix release.
        default: ">=10.8"
        required: true
      next_version:
        description: |
          Specify the version for the next release (e.g., 4.2.0).
          If left blank, the minor version will be automatically incremented.
        required: false
      jira_release_name:
        description: |
          The name of the release version in Jira.
          If blank, the action will try to use the *only* unreleased version in the project.
        required: false
      sonarlint_changelog:
        description: |
          A summary of release notes relevant to the SonarQube IDE extensions.
        required: false

jobs:
  pre-release-checks:
    name: Pre-release checks
    runs-on: ubuntu-latest
    permissions:
      statuses: read
      contents: write
      pull-requests: write
      id-token: write
    steps:
      - name: Check Releasability Status
        uses: SonarSource/release-github-actions/check-releasability-status@03368d584ef1b9bdcc0d786f99246f669ac6030c
      
      - name: Update Rule Metadata
        id: update-rule-metadata
        uses: SonarSource/release-github-actions/update-rule-metadata@03368d584ef1b9bdcc0d786f99246f669ac6030c
      
      - name: Check Rule Metadata Changes
        if: steps.update-rule-metadata.outputs.has-changes == 'true'
        run: |
          echo "::error::Rule metadata changes detected. The generated PR needs to be merged first before continuing with the release."
          echo "::error::Pull Request URL: ${{ steps.update-rule-metadata.outputs.pull-request-url }}"
          echo "::error::Please merge the PR and restart this workflow."
          exit 1

  prepare-release:
    name: Prepare release
    runs-on: ubuntu-latest
    needs: pre-release-checks
    permissions:
      statuses: read
      contents: read
      id-token: write
    outputs:
      release-version: ${{ steps.get-release-version.outputs.release-version }}
      jira-version-name: ${{ steps.get-jira-version.outputs.jira-version-name }}
      release-notes: ${{ steps.get-jira-release-notes.outputs.release-notes }}
      jira-release-url: ${{ steps.get-jira-release-notes.outputs.jira-release-url }}
    steps:
      - name: Get Release Version
        id: get-release-version
        uses: SonarSource/release-github-actions/get-release-version@03368d584ef1b9bdcc0d786f99246f669ac6030c

      - name: Get Jira Version
        id: get-jira-version
        uses: SonarSource/release-github-actions/get-jira-version@03368d584ef1b9bdcc0d786f99246f669ac6030c

      - name: Get Jira Release Notes
        id: get-jira-release-notes
        uses: SonarSource/release-github-actions/get-jira-release-notes@03368d584ef1b9bdcc0d786f99246f669ac6030c

  create-release-ticket:
    name: Create release ticket
    runs-on: ubuntu-latest
    needs: prepare-release
    permissions:
      id-token: write
    steps:
      - name: Create Jira Release Ticket
        id: create-ticket
        uses: SonarSource/release-github-actions/create-jira-release-ticket@03368d584ef1b9bdcc0d786f99246f669ac6030c
        with:
          project-name: ${{env.PROJECT_NAME }}
          short-description: ${{ inputs.short_description }}
          sq-compatibility: ${{ inputs.sq_compatibility }}
          jira-release-url: ${{ needs.prepare-release.outputs.jira-release-url }}
      
      - name: Start progress on ticket
        uses: SonarSource/release-github-actions/update-release-ticket-status@update_release_ticket_status
        with:
          release-ticket-key: ${{ steps.create-ticket.outputs.release-ticket-key }}
          status: "Start Progress"

  publish-github-release:
    name: Publish github release
    runs-on: ubuntu-latest
    needs: [prepare-release, create-release-ticket]
    permissions:
      id-token: write
      contents: write
      actions: write
    steps:
      - name: Publish GitHub Release
        uses: SonarSource/release-github-actions/publish-github-release@update_publish-github-release
        with:
          release-version: ${{ needs.prepare-release.outputs.release-version }}
          release-notes: ${{ needs.prepare-release.outputs.release-notes }}
          release-workflow: 'sonar-release.yml'
          draft: true
