---
name: sonar-release
# This workflow is triggered when publishing a new github release
# yamllint disable-line rule:truthy
on:
  release:
    types:
      - published

jobs:
  release:
    permissions:
      id-token: write
      contents: write
    uses: SonarSource/gh-action_release/.github/workflows/main.yaml@5.17.0
    with:
      publishToBinaries: true
      mavenCentralSync: true
      slackChannel: squad-security-cloud-notifs
