name: Releasability Status
on:
  workflow_run:
    workflows: [Build]  # Name must match the build workflow
    types:
      - completed
    branches:
      - master
      - branch-*

jobs:
  releasability-status:
    name: Releasability status
    runs-on: sonar-s-public
    permissions:
      id-token: write
      statuses: write
      contents: read
    steps:
      - uses: SonarSource/gh-action_releasability/releasability-status@v2
        env:
          GITHUB_TOKEN: ${{ github.token }}
