---
name: sonar-release
# This workflow is used to trigger the release workflow during an automated release
# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
    inputs:
      releaseTagName:
        type: string
        description: Release tag name
        required: true
      releaseId:
        type: string
        description: Release ID
        required: true
      dryRun:
        type: boolean
        description: Flag to enable the dry-run execution
        default: false
        required: false

jobs:
  release:
    permissions:
      id-token: write
      contents: write
    uses: SonarSource/release-github-actions/.github/workflows/sonar-release.yaml@temp_release_workflow
    with:
      releaseTagName: ${{ inputs.releaseTagName }}
      releaseId: ${{ inputs.releaseId }}
      dryRun: ${{ inputs.dryRun }}
      publishToBinaries: true
      mavenCentralSync: true
      slackChannel: squad-security-cloud-notifs
