name: Releasability Status
on:
  workflow_run:
    workflows: [Build]  # Name must match the build workflow
    types:
      - completed
    branches:
      - master
      - branch-*

jobs:
  releasability-status:
    name: Releasability status
    runs-on: sonar-s-public
    steps:
      - name: Debug
        env:
          HEAD_BRANCH: ${{ github.event.workflow_run.head_branch }}
        run: |
            echo "Event Name: ${{ github.event_name }}"
            echo "Workflow Run Conclusion: ${{ github.event.workflow_run.conclusion }}"
            echo "Workflow Run Branch: $HEAD_BRANCH"
      - uses: SonarSource/gh-action_releasability/releasability-status@v2
        env:
          GITHUB_TOKEN: ${{ github.token }}
