name: Check SCA
on:
  pull_request:
  merge_group:

permissions:
  id-token: write
  contents: read

jobs:
  check-sca:
    runs-on: sonar-xs  # Private repos default; use github-ubuntu-latest-s for public repos
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: SonarSource/ci-github-actions/check-sca@v1
        with:
          project-key: "org.sonarsource.php:php"
