name: Ruling Tests

on:
  push:
    branches:
      - master
      - 'branch-*'
      - 'dogfood-on-*'
    paths-ignore:
      - '**/src/main/resources/org/sonar/l10n/*/rules/**'
      - '**/src/main/resources/com/sonar/l10n/*/rules/**'
      - '**sonarpedia.json'
      - '**.md'
  pull_request:
    branches:
      - master
      - 'branch-*'
    paths-ignore:
      - '**/src/main/resources/org/sonar/l10n/*/rules/**'
      - '**/src/main/resources/com/sonar/l10n/*/rules/**'
      - '**sonarpedia.json'
      - '**.md'
  workflow_dispatch:

jobs:
  ruling_tests:
    name: Ruling Tests
    needs: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php_project: [Flysystem, Monica, PhpCodeSniffer, PhpMailer, Psysh, PhpWord, RubixML, PhpSpreadsheet]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: 'recursive'

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: wrapper

      - name: Set Orchestrator home
        run: |
          TODAY=$(date '+%Y-%m-%d')
          echo "TODAY=${TODAY}" >> $GITHUB_ENV
          echo "ORCHESTRATOR_HOME=${GITHUB_WORKSPACE}/orchestrator/${TODAY}" >> $GITHUB_ENV
          mkdir -p ${GITHUB_WORKSPACE}/orchestrator/${TODAY}

      - name: Run ruling tests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SQ_VERSION: LATEST_RELEASE
          KEEP_ORCHESTRATOR_RUNNING: "true"
          PHP_PROJECT: ${{ matrix.php_project }}
        run: |
          source .github/workflows/cirrus-env QA
          ./gradlew its:ruling:integrationTest -Dsonar.runtimeVersion=${SQ_VERSION} --tests "PhpGeneralRulingTest.test${PHP_PROJECT}" --info --build-cache --console plain --no-daemon

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ruling-test-results-${{ matrix.php_project }}
          path: '**/test-results/**/*.xml'
