name: Toggle lock branch

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
        default: "master"
  workflow_dispatch:    # Triggered manually from the GitHub UI / Actions
    inputs:
      branch:
        description: "Branch to lock"
        required: true
        default: "master"

jobs:
  ToggleLockBranch_job:
    name: Toggle lock branch
    runs-on: ubuntu-latest-large
    permissions:
      id-token: write
    steps:
      - id: secrets
        uses: SonarSource/vault-action-wrapper@v3
        with:
          secrets: |
            development/github/token/{REPO_OWNER_NAME_DASH}-lock token | lock_token;
            development/kv/data/slack token | slack_api_token;
      - uses: sonarsource/gh-action-lt-backlog/ToggleLockBranch@v2
        with:
          github-token: ${{ fromJSON(steps.secrets.outputs.vault).lock_token }}
          slack-token: ${{ fromJSON(steps.secrets.outputs.vault).slack_api_token }}
          slack-channel: squad-security-cloud-notifs
          branch-pattern: ${{ inputs.branch }}
